# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'fiestapp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for fiestapp
  pod 'Firebase/Core'
  pod 'Firebase/Auth'

  # Pods for Facebook
  pod 'Bolts'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'Firebase/Database'

  # Pods for SwipeCards
  pod 'Koloda'
end
